// GENERATED by @edgedb/generate v0.5.5

import type {Executor} from "edgedb";


export type GetTodosAndClientsReturns = {
  "todos": Array<{
    "id": string;
    "complete": boolean;
    "content": string;
    "todoID": string;
  }>;
  "clients": Array<{
    "id": string;
    "clientID": string;
    "lastMutationID": number;
  }>;
};

export function getTodosAndClients(client: Executor): Promise<GetTodosAndClientsReturns> {
  return client.queryRequiredSingle(`\
select {
  todos := (select Todo {*}),
  clients := (select ReplicacheClient {*})
}`);

}
