// GENERATED by @edgedb/generate v0.5.5

import type {Executor} from "edgedb";


export type GetTodosAndClientsReturns = {
  "todos": Array<{
    "updated_at": Date | null;
    "created_at": Date | null;
    "id": string;
    "version": number | null;
    "replicache_id": string;
    "complete": boolean;
    "content": string;
  }>;
  "clients": Array<{
    "id": string;
    "client_id": string;
    "last_mutation_id": number;
  }>;
};

export function getTodosAndClients(client: Executor): Promise<GetTodosAndClientsReturns> {
  return client.queryRequiredSingle(`\
select {
  todos := (select Todo {*}),
  clients := (select ReplicacheClient {*})
}`);

}
